# Generated by Django 4.2.3 on 2023-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_profile_facebook_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media_handle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
